### ISSUE TITLE
[Bug]: Widget guides don't show for first item

### ISSUE THREAD

**Issue by p4-k4** [akinsho/flutter-tools.nvim#106]
Widget guides don't show for first item but do for every subsequent item in the list. Items being of `Widget` types.

**To Reproduce**

Make a list of widgets.

**Expected behavior**
Expect to see the widget guides consistently across all widgets in a list.

**Screenshots**
[
![](https://i.imgur.com/QGGElVa.png)
](url)

**System information**

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter
Framework • revision 18116933e7 (4 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by akinsho** [comment]
Thanks for raising this and providing a good amount of detail + a screenshot. So there are definitely still quite a few issues here and there with the widget guides, which is why they are still off by default. I can confirm that this is something I see as well and could be as simple as an off by one error since lua is one based, or could be something more complex. In either case will leave this open till it is resolved, but I'm busy with none neovim plugin work at the moment so won't be getting to this for a while.

If anyone is willing to contribute, please let me know, and I'll try and provide advice for a fix.

**Comment by p4-k4** [comment]
Was anticipating that you'd be well aware of it especially given you've indicated it's experimental and also reflects in the README screenshots, was more creating an issue for it just in case :)

Thanks heaps for this btw. Cheers
