### ISSUE TITLE
Support: How do you detach from a running flutter process?

### ISSUE THREAD

**Issue by joshpetit** [akinsho/flutter-tools.nvim#111]
Hey, thanks for making this awesome plugin :smile: 

I was wondering if it was possible to detach from the running flutter process? This is something that's capable in coc-flutter

**Comment by akinsho** [comment]
@joshpetit you can quit/close use the `FlutterQuit` command to close the running application. All the available commands should be documented in the README, although I might have forgotten one or two

**Comment by joshpetit** [comment]
@akinsho Yea, `FlutterQuit` works fine. `FlutterDetach` would stop the process from running inside the terminal but leave it running on the phone. It may just be something coc-flutter implemented so doesn't really need to be in here. The command is called `flutter.dev.detach` and described as "Detach server".

**Comment by akinsho** [comment]
Ah thanks for clarifying @joshpetit that is different functionality. I never used that whilst using `coc-flutter` what would the use case for that be? I definitely haven't implemented all the commands it does, primarily because I only wanted to add stuff that had a clear benefit. If it's native to the flutter binary then it shouldn't be too hard to add, although I guess before that it'd be good to determine if it will be useful to a lot of people.

**Comment by joshpetit** [comment]
@akinsho , no problem. It left the app running on the phone. I often need to demo the app, so instead of having to start the build process again to get the debug apk installed, I can just detach the debug apk and demo that after I'm done working. If I detach it also makes the version that remains on the phone the most recent, since when I do flutter quit and reopen the app later from the launcher, it's usually a few iterations previous older. 

That's the main benefit, but if it's not a usecase you can see a lot of people using then there's not much reason to implement it honestly haha. I can see it being useful and also something no one ever really uses :sweat_smile:

**Comment by akinsho** [comment]
@joshpetit if you are up for submitting a PR to add that then I'm fine with the addition, personally I don't think I'd use it but could see how someone else might perhaps. In either case I'll accept it as a PR but need to focus on adding as general as possible functionality personally since I have limited time so probably won't add this myself.

**Comment by joshpetit** [comment]
finished!
