### ISSUE TITLE
[Bug]: Flags are ignored when device is not initally specified

### ISSUE THREAD

**Issue by joshpetit** [akinsho/flutter-tools.nvim#118]
**Describe the bug**

When the device is not passed to the `FlutterRun -t <path>` command, it ignores the `-t <path>` parameter

**To Reproduce**

1. Have multiple devices you can run
2. FlutterRun -t <path>
3. See the prompt pop up asking for which device
4. Click on a device
5. See that the flutter process is run with `lib/main.dart` as the target rather than what you specified in `-t`

**Expected behavior**
Expect it to use the `-t` flag originally passed

**System information**

- OS: Arch
- Flutter version: 2.8.1
- Is flutter in $PATH: yes
- neovim version: 0.6.1

**Comment by akinsho** [comment]
Hi @joshpetit I'm not familiar with the `-t` flag (I've never had cause to use it) tbh and didn't really design the `FlutterRun` command to be a perfect match for `flutter run` in the terminal, it definitely doesn't behave exactly the same behaviour since it might not necessarily catch all the relevant arguments or be able to. If you're willing to investigate I can point you to where you might want to look to fix this issue.

**Comment by joshpetit** [comment]
ok cool, I'll take a look, some help would be appreciated.

**Comment by akinsho** [comment]
Gonna close this out now #119 is merged, thanks for the contribution @joshpetit 🥇
