### ISSUE TITLE
[Bug]: `%` not passing file path

### ISSUE THREAD

**Issue by joshpetit** [akinsho/flutter-tools.nvim#123]
**Describe the bug**

**To Reproduce**
1. Run :FlutterRun -t %
2. See error

**Expected behavior**

**Screenshots**

**System information**

- OS:
- Flutter version: 2
- Is flutter in $PATH: yes
- neovim version: 0.6

**Additional context**

You can pass a `%` to most commands in neovim and it will expand to the file path, but flutterun takes it as a literal argument. 

Generally I'd offer to fix this, but I don't what could possibly cause this.

**Comment by akinsho** [comment]
Hi @joshpetit, so this isn't native behaviour for most user defined commands, the only commands that automatically expand the percent symbol are native vim commands. I don't actually think this is expected behaviour since it's not normal for user-defined commands to just do this. Usually a plug-in author has to do the work of expanding special symbols to emulate this native functionality. I actually have another plugin where I've had to do this and it can be quite involved. 

I think in order to get this functionality I recommend mapping the percent symbol or %%, for example in your config to expand to the file path. You can use `cnoremap %% expand('%')` or something like that.

**Comment by joshpetit** [comment]
That's beautiful, thank you

**Comment by joshpetit** [comment]
Just as in FYI doing cnoremap wouldn't work for this, I'm just doing <C-R> % to get the path from % buffer.
