### ISSUE TITLE
The foreground color does not adapt to the background color

### ISSUE THREAD

**Issue by fitrh** [akinsho/flutter-tools.nvim#129]
**Describe the bug**
Enabling `lsp.color` with `background = true` does not change the `guifg` of the text to black or white as in the README screenshot.

**To Reproduce**

1. Create a flutter project
2. open the `main.dart` file
3. Define `const white = Color(0xFFFFFFFF);`

**Expected behavior**
`guifg` for `Color(0xFFFFFFFF)` is black.

**Screenshots**
![20220215_184937_area](https://user-images.githubusercontent.com/55179750/154048560-b0fc0d66-a2c7-4388-bb35-5bc2e830214b.jpg)

**System information**

- OS: Arch Linux 5.16.8-arch1-1
- Flutter version: 2.10.1
- Is flutter in $PATH: Yes
- neovim version: NVIM v0.7.0-dev+1076-gf378df846

**Comment by akinsho** [comment]
@fitrh I wouldn't describe this as a bug since the behaviour of making the colour black or white is not specifically advertised functionality. FWIW this functionality was copied from a PR in nvim without much tweaking tbh I'm not really likely to go wild with trying to derive specific colour behaviours based on the background etc. essentially it is taken as is and only here until the functionality is officially supported in nvim core. In the screenshot above the text to my mind is visible which is good enough, i.e. this is the most that this plugin will try to do.

**Comment by fitrh** [comment]
I just skimmed the diff and found this [function](https://github.com/akinsho/flutter-tools.nvim/pull/125/files#diff-86919e16aa6139040d1a6b9e69abf7c7d92c8e25b8807439ed8a94f61c61bf81R109-R119), if I understand it correctly, it set the foreground to black or white based on the result of `perceived_lightness` right ?

**Comment by fitrh** [comment]
@akinsho how you can get black or white foreground as in the README ?

![20220215_215133_area](https://user-images.githubusercontent.com/55179750/154077254-32f77a23-4fe3-4702-8904-15a06fd5ff09.jpg)

The text is visible because I zoomed it, using my daily font size will make it hard to read.

**Comment by akinsho** [comment]
@fitrh I didn't write this logic, and so I don't know a great deal about how it works, if you're willing to dig in and raise a PR to make this change then I'm happy to review but as I mentioned I only implemented this because another user requested it and there was some code lying around in nvim core that added this functionality. I don't want to go down the rabbit hole of basically building a mini colour presentation plugin within this plugin and I don't personally intend to massively tweak the logic I borrowed from nvim core since I hope eventually it will be available natively.

**Comment by akinsho** [comment]
To workaround this issue maybe use one of the other options e.g. `foreground` or `virtual_text`

**Comment by fitrh** [comment]
The cause is treesitter, if I disable treesitter highlight, the color foreground highlighted correctly, also because of this, set `foreground = true` does not work.

![20220215_234433_area](https://user-images.githubusercontent.com/55179750/154098729-1ba7a49d-d26a-4096-95b1-d5e138ce9e92.jpg)

**Comment by akinsho** [comment]
Okay I've looked into this a bit more, and it was because Treesitter's highlighting overrides the highlights set by this plugin, so I've increased the priority of the highlights for this plugin, so the foreground should always be black or white
