### ISSUE TITLE
[Bug]: line value outside range warning when calling extract method/widget more than once 

### ISSUE THREAD

**Issue by bjornevik** [akinsho/flutter-tools.nvim#132]
**Describe the bug**
```
call plug#begin('~/.config/nvim/plugged')
  Plug 'nvim-lua/plenary.nvim'
  Plug 'akinsho/flutter-tools.nvim'
call plug#end()

lua << EOF
  require("flutter-tools").setup{}
EOF
```

When using the extract method/widget code action more than once  a 'line value outside range' warning will be displayed.
This warning will also be displayed if you undo the code action. The action/undo will execute despite the error message.
Closing and opening nvim will again allow you to do 1 extract action before the warning is shown.

```
Error executing vim.schedule lua callback: .../plugged/flutter-tools.nvim/lua/flutter-tools/labels.lua:15: line value outside range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        .../plugged/flutter-tools.nvim/lua/flutter-tools/labels.lua:15: in function 'render_labels'
        .../plugged/flutter-tools.nvim/lua/flutter-tools/labels.lua:39: in function 'func'
        ...gged/flutter-tools.nvim/lua/flutter-tools/utils/init.lua:230: in function 'handler'
        ...r/neovim/HEAD-046950f/share/nvim/runtime/lua/vim/lsp.lua:796: in function ''
```

**To Reproduce**

1. Create blank flutter project and cd into it
2. nvim lib/main.dart
3. Navigate to something you want to extract
4. :lua vim.lsp.buf.code_action() and pick either extract widget or extract method
5. undo || navigate to another thing you want to extract and repeat 4.

**Expected behavior**
For the code action to execute without displaying a warning.

**Screenshots**
![Screenshot from 2022-02-20 15-45-44](https://user-images.githubusercontent.com/5864000/154849178-46cf4942-85e0-4b46-aae6-e1c4ce6ef1e0.png)

**System information**

- OS: Ubuntu 20.04.3 LTS && macOS Monterey 12.2.1
- Flutter version: 
```
Flutter 2.11.0-0.0.pre.633 • channel master • https://github.com/flutter/flutter.git
Framework • revision 54a9d65282 (21 hours ago) • 2022-02-19 10:09:26 -0800
Engine • revision f6ea6186ee
Tools • Dart 2.17.0 (build 2.17.0-125.0.dev) • DevTools 2.11.0
```
- Is flutter in $PATH: Yes
- neovim version: 
```
NVIM v0.7.0-dev+1067-ga1f34b248
Build type: Release
LuaJIT 2.1.0-beta3
```

**Additional context**
I did mention this in #130 as well, but since it's a different problem entirerly I thought it best to open a separate issue.

The actual actions / undos seem to execute perfectly fine, it's just a somewhat annoying error message so I don't know how critical it is to be fixed.

**Comment by akinsho** [comment]
@bjornevik thanks for raising this. In the example you mentioned it doesn't sound like you save the file after completing an extract code action. So it's unlikely that the language server will know that the file has changed. So it will have a reference to incorrect line numbers since the line numbers will now be different. Can you try again but making sure you save in between code actions and see whether or not that solves the issue?

**Comment by bjornevik** [comment]
@akinsho Same result with saving.

**Comment by bjornevik** [comment]
It does not happen if I save and then reload the buffer with :e

**Comment by akinsho** [comment]
I've pushed a fix which should stop the disruptive error. Ultimately though the fix I think should maybe be in nvim core since making sure the buffer is sync with the language server isn't really the job of this plugin but nvim-core. Since I think that's the issue

**Comment by bjornevik** [comment]
@akinsho looked a bit through `:h nvim_buf_set_extmark`, could we potentially set `strict = false` (introduced in  [neovim#17001](https://github.com/neovim/neovim/pull/17001)) in the actual call?

**Comment by akinsho** [comment]
@bjornevik thanks for pointing that out, although I don't think that's a solution to this issue. The problem isn't really with the extmark function but rather with the fact that when you use the extract method/widget functionality this changes the buffer content so then trying to place widget labels doesn't work since the buffer has changed but the lsp seems to be unaware of the change till the buffer is reloaded. I think the solution would be figuring out why the lsp is not aware of the updated buffer state after the refactor and so why subsequent labels requests don't know that the buffer has changed.
