### ISSUE TITLE
outline.lua error

### ISSUE THREAD

**Issue by syarifs** [akinsho/flutter-tools.nvim#19]
i just install the plugin with vim-plug and initialize it using default setting, but i get this message.
```
Error detected while processing /home/syarif/.dotfiles/config/nvim/init.vim: line   19:
E5113: Error while calling lua chunk: vim.lua:129: ...plugged/flutter-tools.nvim/lua/flutter-tools/outline.lua:46: invalid escape sequence near '"'
```

**Comment by vicecaycedo** [comment]
What operating system are you using?

**Comment by akinsho** [comment]
@syarifs looking at the line where the error is being thrown it's just the declaration of one of the characters used in the outline. As far as I know this is valid lua 5.1 syntax and hasn't caused any issues for me. I need more information about your specific setup to debug. I don't think it should be anything OS specific maybe but not sure since I don't use windows so wouldn't know if it'd cause an issue there

**Comment by syarifs** [comment]
@akinsho  @vicecaycedo 
my environment setup
```
Manjaro 21.0
Lua 5.2
LuaJIT 2.0.5
NVIM v0.5.0-dev+1133-g0869cbd55
```

**Comment by akinsho** [comment]
@syarifs your lua version should be `5.1` although neovim doesn't error or anything using `5.2` it specifically targets lua 5.1. My understanding is that lua 5.1 and 5.2 are essentially different languages with breaking changes between versions. It might be that the syntax I'm using no longer works for Lua 5.1 although I'm not a 100% sure on that. It's the best glaring difference I can see though.

Also I don't think luajit is compatible with versions other than 5.1 anyway so think maybe you're losing the benefits of luajit so should use 5.1 anyway since this will come up later I think

**Comment by khalid151** [comment]
@akinsho  I'm having the same issue. But I don't quite understand what you said about lua versions. As far as I know, neovim comes with lua 5.1 built-in (`:help lua`).

Anyway, this seem to be something with LuaJIT, it couldn't parse unicode escape sequences. Inputting the literal characters solves the problem for me.

```diff
diff --git a/lua/flutter-tools/outline.lua b/lua/flutter-tools/outline.lua
index a3362d0..b472f1f 100644
--- a/lua/flutter-tools/outline.lua
+++ b/lua/flutter-tools/outline.lua
@@ -37,17 +37,17 @@ local markers = {
 }
 
 local icons = setmetatable({
-  TOP_LEVEL_VARIABLE = "\u{f435}",
-  CLASS = "\u{f0e8}",
-  FIELD = "\u{f93d}",
-  CONSTRUCTOR = "\u{e624}",
-  CONSTRUCTOR_INVOCATION = "\u{fc2a}",
-  FUNCTION = "\u{0192}",
-  METHOD = "\u{f6a6}",
-  GETTER = "\u{f9f}",
-  ENUM = "\u{f779}",
-  ENUM_CONSTANT = "\u{f02b}",
-  DEFAULT = "\u{e612}",
+  TOP_LEVEL_VARIABLE = "",
+  CLASS = "",
+  FIELD = "綠",
+  CONSTRUCTOR = "",
+  CONSTRUCTOR_INVOCATION = "ﰪ",
+  FUNCTION = "ƒ",
+  METHOD = "",
+  GETTER = "ྟ",
+  ENUM = "",
+  ENUM_CONSTANT = "",
+  DEFAULT = "",
 }, {
   __index = function(t, _)
     return t.DEFAULT
```

**Comment by akinsho** [comment]
@syarifs thanks for providing the icons 👍🏿 . so regarding `lua` in `nvim` what I meant is that it isn't contained in nvim's source code or something. It needs to be bundled by whatever distribution channel is shipping nvim e.g. `apt` or `aur`. Technically a user can run nvim despite not having `lua 5.1` installed it's what nvim targets but a user could still be using lua `5.2` etc. I don't know that this escape code issue is that or not.

Can you run `lua -v` and post what version you are on? Just out of curiosity. I'll switch this to use the actual icons, since 🤷🏿 but it's important to note that I (and other plugin developers) will be targeting lua 5.1 so if use some functionality that works in `5.1` but doesn't in `5.2` or whatever other version someone is using I won't change it (depending on what it is)

**Comment by khalid151** [comment]
@akinsho It's `Lua 5.4.3` but I have multiple lua versions installed (including `5.1`). But as I mentioned earlier, the error thrown is basically the same when I run it in LuaJIT. `5.2` had a different error message.

**Comment by akinsho** [comment]
@khalid151 I have no idea how this will all behave with multiple versions, there are also versions of luajit as well right (way more lua in depth knowledge than I have). Anyway I've changed it to use icons directly. We'll see if further issues arise but as I've mentioned I'm going to work with the assumption that if it works with the specific versions that neovim accept then it is valid 🤷🏿
