### ISSUE TITLE
Spawning language server with cmd: `./bin/dart` failed.

### ISSUE THREAD

**Issue by nuxry** [akinsho/flutter-tools.nvim#194]
Full error message: Spawning language server with cmd: `./bin/dart` failed. The language server is either not installed, missing from PATH, or not executable.

**To Reproduce**
Open dart file in non-flutter project.

**Expected behavior**
Have the Lsp working.

**System information**

- OS: Manjaro Linux
- Flutter version: no installed.
- Is flutter in $PATH:
- neovim version: v0.8.0

My flutter-tools.nvim config:
```dart
return {
  ["akinsho/flutter-tools.nvim"] = {
  requires = "nvim-lua/plenary.nvim",
  config = function()
    require("plugin.flutter-tools.config")
    require("plugin.flutter-tools.keymap")
  end,
  ft = "dart",
  }
}
```

Note: I've tried it in both NvChad and LunarVim, I don't think it's a problem with lazy loading.

**Comment by akinsho** [comment]
There's really nothing in this bug report that I can use to fix or reproduce this issue. I can confirm that this plugin works on macOS and Linux if flutter is installed via conventional methods. Please try to get a *minimal init.lua* with exact reproduction steps, although be forewarned that I get many issues which relate to how a user has installed flutter and set their path and I don't personally get involved in debugging this sort of thing as it would otherwise occupy most of my free FOSS time
