### ISSUE TITLE
[Issue]: Flutter Run with Visual Log not shown 

### ISSUE THREAD

**Issue by Nanank-kho** [akinsho/flutter-tools.nvim#212]
Setting for visual log,

I want to figure visual log like this but visual log in bottom like DAP
![image](https://user-images.githubusercontent.com/12078569/221416178-fe3988a8-74cb-494f-9f70-c8cd69972fbe.png)

or how to close left panel of DAP and only show visual log in bottom like vscode
![Screenshot 2023-02-26 at 21 23 10](https://user-images.githubusercontent.com/12078569/221416452-f567a10d-e454-4353-b05f-58cbe1891236.png)

setting plugins
```
debugger = {
		enabled = true,
		run_via_dap = true,
	},
```
thanks

**Comment by akinsho** [comment]
@Nanank-kho the appearance in the screenshot of my editor is because I was running it without dap, whilst using dap, it controls the output of flutter and so that goes into dap's repl ths is just how that is. You can tweak dap to behave how you want or tweak the dapui windows but that is your responsibility and doesn't relate to this plugin really.
