### ISSUE TITLE
Can't use commands

### ISSUE THREAD

**Issue by Neeraj029** [akinsho/flutter-tools.nvim#224]
Hi!

I just installed flutter-tools using lazy.nvim, lsp for dart works fine but Flutter commands aren't showing up
I just used the code given for lazy.nvim on the install section.
![image](https://user-images.githubusercontent.com/66945520/225533252-5491743a-c856-4cc9-bcff-eda5f3d49ac3.png)

Any help would be appreciated!

**Comment by akinsho** [comment]
Hi @Neeraj029,

so you're missing some crucial information from this issue i.e. how do you configure this plugin did you call setup at some point in the plugin configuration? there isn't an example of a minimal configuration to show what hasn't worked and under what circumstance.

I suggest carefully going through the README about how this plugin is started and making sure you've done that in a way that works with lazy.nvim. As a lazy.nvim user myself I know that this plugin will work with it so this issue is a configuration issue.

**Comment by Neeraj029** [comment]
Hi @akinsho 
![image](https://user-images.githubusercontent.com/66945520/225573473-189c792d-2b3a-4d8b-ab79-529af8cacebc.png)
I'm doing this

**Comment by akinsho** [comment]
@Neeraj029 in general it's better to paste code rather than a screenshot of code so I can easily copy and paste what you are showing me. In this case it's clear from your setup that you are not explicitly calling setup for this plugin. In general I strongly advice you read in detail the README of this plugin and of the configuration framework you are using as this is an important step that you are missing and maybe don't understand.

you need something like
```lua
config = function()
	require('flutter-tools').setup()
end
```

I think you should be able to handle the rest by carefully reading the bits of documentation for these tools and this doesn't need to be an ongoing issue on this repo
