### ISSUE TITLE
Support file rename with imports update

### ISSUE THREAD

**Issue by sidlatau** [akinsho/flutter-tools.nvim#233]
Imports are not automatically updated when a file is renamed. Dart LSP actually supports imports update via `workspace/willRenameFiles`, these changes need to be retrieved from the language server and applied after renaming.

This functionality in the future may be supported natively in NeoVim: https://github.com/neovim/neovim/issues/20784

But until that time I have implemented it here: https://github.com/sidlatau/dart-lsp-refactorings.nvim . I am using it without issues for several months. There are actually only two public functions: `require("dart-lsp-refactorings").rename()` that may be used instead of `vim.lsp.buf.rename()` and `require("dart-lsp-refactorings").on_rename_file` that may be used when renaming a file in file explorer (i.e neo-tree).

@akinsho, what is your opinion on bringing these or similar functions (with any needed code adjustments) to `flutter-tools` plugin? I see the benefits of having `dartls` related code in the same place. Also, more people may discover this functionality.
Or is it better to have it as a separate plugin? I understand that these functions are quite custom, plus it will add code that may require additional maintenance.

Related to: https://github.com/akinsho/flutter-tools.nvim/issues/39

**Comment by akinsho** [comment]
@sidlatau sorry been a bit busy, I'm definitely open to adding this. FWIW although I personally don't have the time or bandwidth to try to emulate everything (for flutter) in Android Studio or VSCode I think the general goal of this plugin is to make developing flutter/dart apps on neovim as nice as possible and take inspiration from those tools as the gold standards for flutter dev.

Anyway all that being said the only reason I had not added this is that I had hoped that a native version would have been merged by now. Another reason is that dart LS added in some options around this.
https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md#client-workspace-configuration

i.e. so we already get renaming a file for free if the class matches the file, the other one that is supported there is `dart.updateImportsOnRename` which I guess this feature would add support for until there is a neovim native solution

Looking through your project briefly I think the language server is probably doing some of this work that that plugin does automatically and the only change needed here to make all this work is to add support for `workspace/willRenameFiles` once we have signaled that support to the server and have handlers for it I think it should work.

I wonder if we would actually need separate commands since I'd love to do this in such a way that it is easy to deprecate once neovim adds support for this

**Comment by sidlatau** [comment]
@akinsho, I created PR with a suggestion to introduce a separate command `FlutterRename` to support this `dart.updateImportsOnRename` setting. The functionality is quite a niche, but it still adds value, when using it there is no need to manually update all imports after class rename.
