### ISSUE TITLE
[BUG] How do I disable inline error messages?

### ISSUE THREAD

**Issue by JPFrancoia** [akinsho/flutter-tools.nvim#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![screen-2023-04-09-12-09-24](https://user-images.githubusercontent.com/2399090/230769086-37a14876-6116-4db9-a452-d7415ec4309d.png)

I have been trying to disable the inline error messages (see the message displayed in red in the screenshot) for a couple of hours now, with no success.

### Expected Behavior

There should be an option to easily disable the inline messages. I want ale to handle them, for consistency with my settings for all other languages.

### Steps To Reproduce

Relevant section of my init.vim:

```
"Tools for Flutter
Plug 'akinsho/flutter-tools.nvim'

call plug#end()
filetype plugin indent on    " required

...

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ 'python' : ['pylsp'],
    \ 'go' : ['gopls'],
    \ 'sql': ['sql-language-server', 'up', '--method', 'stdio'],
    \ 'yaml': ['yamlls'],
    \ 'terraform': ['terraform-ls', 'serve'],
    \ 'dart': ['dart', 'language-server'],
    \ }

lua <<EOF
EOF
```

### Environment

```Markdown
- OS: Archlinux
- Flutter version: 3.7.10
- Is flutter in $PATH: yes
- neovim version: v0.9.0
```

**Comment by akinsho** [comment]
@JPFrancoia the error messages you are seeing are not controlled by flutter-tools.nvim these are native to neovim's language server client and are controlled by your settings in `vim.diagnostic.config`. In order to use this plugin properly you will need to have an understanding of how neovim's LSP works. I highly recommend reading through `:help vim.diagnostic`.

In short this isn't an issue with this plugin specifically. Also it's important to note that this plugin configure the dart language server, this is documented in my README, it should not also be setup using something like ale or some other plugin. This plugin is intended for use with neovim's LSP only not a mixture of it and other language server plugins as this would duplicate the functionality.

I've tried to cover this point as the first item in the README, so that new users of neovims lsp have a better understand. Please have a read through the initial section and take some time to read the associated links as well.

**Comment by akinsho** [comment]
Just adding a direct link to the section of the README where this is described: https://github.com/akinsho/flutter-tools.nvim#new-to-neovims-lsp-client

**Comment by JPFrancoia** [comment]
> @JPFrancoia the error messages you are seeing are not controlled by flutter-tools.nvim these are native to neovim's language server client and are controlled by your settings in vim.diagnostic.config.

Yes, true. What led me to believe it was flutter-tools was the fact that if I commented the plugin in init.vim, the messages disappeared. Which somehow is really weird, because I had this in my `ftplugin/dart/dart_config.vim` file:

```
"Don't display warning/errors from the language client, let ALE handle it
let g:LanguageClient_diagnosticsEnable=0
```

By adding also this to the file, I got rid of the messages while keeping fluttertools enabled:

```
lua <<EOF
vim.diagnostic.disable()
EOF
```

> In short this isn't an issue with this plugin specifically. Also it's important to note that this plugin configures the dart language server, this is documented in my README, it should not also be setup using something like ale or some other plugin. This plugin is intended for use with neovim's LSP only not a mixture of it and other language server plugins as this would duplicate the functionality.

That makes sense, especially for new users, but I'm interested only in the code action feature of this plugin. I also want all my programming languages to be setup in the same way because I don't want to maintain 42 different kinds of setup.
