### ISSUE TITLE
I am just wondering Is there a feature previewing icon? Like visualizing colors

### ISSUE THREAD

**Issue by Cruising0904** [akinsho/flutter-tools.nvim#242]
Is there a way to configure this? 
Looked though issues and doc couldn't find it.

Also looking for a function auto fix const or final thingy on save. 

Thanks for the awesome plugin if it was not I couldn't manage to code in neovim 😀

**Comment by akinsho** [comment]
@Cruising0904 because neovim is a terminal based program showing images is not very straightforward, some terminal emulators support this but neovim itself does not support it yet.

> Also looking for a function auto fix const or final thingy on save.

This is an lsp server code action not strictly controlled by this plugin, you might be able to work something out but it's not specifically related to this plugin

**Comment by Cruising0904** [comment]
Thanks. I understood :)
