### ISSUE TITLE
dartls won't run without setting $PATH

### ISSUE THREAD

**Issue by andersevenrud** [akinsho/flutter-tools.nvim#30]
If I don't explicitly add the Flutter bin directory to `$PATH` I get the following error:

```
Client 1 quit with exit code 64 and signal 0
```

This is using the following setup (I tried adding the executable name there too as well as some other combinations, with same result):

```lua
require'flutter-tools'.setup{
    flutter_path = '/mnt/ssd-data/flutter/bin'
}
```

If I start a new terminal session, update the `$PATH`, then confirm it:

```
**bunch of paths**:/mnt/ssd-data/flutter/bin
```

Then launch neovim, everything works like expected.

**Comment by akinsho** [comment]
@andersevenrud thanks for trying out the plugin 👍🏾 

The first error is the language server not finding the correct path, the plugin expects users to have setup flutter such that it is available in your path since otherwise there isn't a clear way to find the binary. The [installation instructions](https://flutter.dev/docs/get-started/install/macos) indicate that putting flutter in your path is a normal part of setup.

The alternative is to explicitly set the path that the plugin should use using either a full path or a command which returns the full path such as `asdf where flutter`. 

Not sure if that clarifies, in your case I'm not sure if you are trying to avoid having it in your path or something? in which case if it isn't in your path then as you've found you need to set it up the way you have

**Comment by andersevenrud** [comment]
> I'm not sure if you are trying to avoid having it in your path or something?

This is exactly what I'm trying to achieve.

> in which case if it isn't in your path then as you've found you need to set it up the way you have

Sadly this does not seem to work. I'll give it a few more attempts and get back to you.

**Comment by akinsho** [comment]
@andersevenrud I think it might be that the path to flutter should be `/mnt/ssd-data/flutter/bin/flutter` since what you are trying to pass the the plugin is the full path of the executable. In your example what you are using is still a folder which probably contains the executable itself. What you use in that field should work if you ran it in the terminal e.g.
```
<my-full-path>/bin/flutter -h
```
should work in order for the plugin to work since this is what it would use instead of a `flutter -h` binary available in your path

**Comment by akinsho** [comment]
sorry I missed the bit there when you said that didn't work, does it work in the terminal e.g. path you used -h, does that print anything?

**Comment by andersevenrud** [comment]
> I think it might be that the path to flutter should be /mnt/ssd-data/flutter/bin/flutter since what you are trying to pass the the plugin is the full path of the executable

If I try to set the executable as the path then I get an error saying it expects a directory:

```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp.lua:219: root_dir: expected directory, got lib
stack traceback:
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:219: in function 'validate_client_config'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:636: in function 'start_client'
        ...vim/plugins/flutter-tools.nvim/lua/flutter-tools/lsp.lua:133: in function 'callback'
        ...gins/flutter-tools.nvim/lua/flutter-tools/executable.lua:128: in function <...gins/flutter-tools.nvim/lua/flutter-tools/executable.lua:127>
```


When I run the suggested command in the terminal it executes fine and gives the help printout.

```
[I] ➜ /mnt/ssd-data/flutter/bin/flutter -h
Manage your Flutter app development.

-- lots of text ---
```

**Comment by akinsho** [comment]
@andersevenrud lemme put together a PR looking through my logic a lot of it presumes that flutter or dart will be available on the path which it checks via `vim.fn.executable('flutter')` even if the directory is not standard. Will do some tweaking to see if I can get it to work when they aren't

**Comment by akinsho** [comment]
@andersevenrud can you try #33 and see if that fixes things for you?

**Comment by andersevenrud** [comment]
That seems to have done the trick. I now set my `flutter_path` to the full path of the executable and it fires up just as it did with lspconfig. Nice!

**Comment by akinsho** [comment]
Awesome, will make sure it doesn't break anything for anyone else then merge it 👍🏾

**Comment by andersevenrud** [comment]
Ah. Here we go :nerd_face:  Thank you very much for the quick response time and resolution!
