### ISSUE TITLE
[Feature Request] Show and load emulators installed with Genymotion

### ISSUE THREAD

**Issue by sontungexpt** [akinsho/flutter-tools.nvim#368]
[Feature Request] Can you integrate [Genymotion](https://www.genymotion.com)

**Comment by akinsho** [comment]
This seems very much out of scope for this plugin which is just a wrapper around the dart language server and flutter tooling. Integrating a third party emulator tool is not something I think that this plugin is for. Obvs if other contributors feel otherwise who are closer to this tooling let me know but doesn't seem likely
