### ISSUE TITLE
Issues with lspsga

### ISSUE THREAD

**Issue by tami5** [akinsho/flutter-tools.nvim#45]
Hey @akinsho, I got around to experiment with flutter, and I'm so glad you have worked an development environment for it. 

There some issue that break float window and some features related to lspsaga code actions, If you are still using can you take a look.

Thanks

**Comment by akinsho** [comment]
@tami5 thanks for trying the plugin out. I also use LspSaga with this plugin, what kind of issues are you seeing can you give me more details on specific issues you are seeing.

Regarding the size of the floating windows etc. these are issues I think with lspsaga itself rather than anything that this plugin handles. I've actually raised an issue about the size of floats in lspsaga since dartls sends *a lot* of docs and they occasionally break.
e.g. https://github.com/glepnir/lspsaga.nvim/issues/159

**Comment by tami5** [comment]
actions without flutter-tools

![Screen Shot 2021-05-14 at 3 06 36 PM](https://user-images.githubusercontent.com/65782666/118268371-fceed680-b4c5-11eb-8046-5d78e8638611.png)

with flutter-tools

![Screen Shot 2021-05-14 at 3 09 13 PM](https://user-images.githubusercontent.com/65782666/118268681-5fe06d80-b4c6-11eb-84c6-c99c8cdfa6f8.png)

setup method

```lua
lang['akinsho/flutter-tools.nvim'] = {
  config = function ()
    return require("flutter-tools").setup{} -- use defaults
  end
}

```

when I exit the popup action, escape the main window, the second window get filled with the actions and  when I click on one of the options I get

![Screen Shot 2021-05-14 at 3 11 10 PM](https://user-images.githubusercontent.com/65782666/118268863-9fa75500-b4c6-11eb-9f3f-bad8a78c3789.png)


edit: Okay adding the setup function as part of lsp attach function seem to fix the issue 🤭. 

Maybe this can be noted :D, oh packer has some wired things

**Comment by akinsho** [comment]
@tami5 when you say as part of the `lsp_attach` function that doesn't sound right. This plugin should be used *completely separately* to lspconfig you should not enable dartls via lspconfig otherwise it will create two clients since this plugin already starts and manages the dartls server on its own. You can pass a custom `on_attach` in the `lsp` field of the config but none of your config should be happening inside lspconfig's stuff

**Comment by tami5** [comment]
Do you mean to say that I shouldn't call setup function for dartls (even without any modifications to dartls)?

here my attach function

```lua
local on_attach = function()
  if vim.bo.filetype == "dart" then
    require("flutter-tools").setup{} -- use defaults
  end

  require'lsp_signature'.on_attach()
  -- vim.cmd("autocmd CursorHold * lua require'lspsaga.diagnostics'.show_line_diagnsotics()")
  require'internal.map'(mappings)
  if vim.g.Lspdebug == true then
    print(vim.bo.filetype .. " client is attached")
  end
end
```

The reason I'm using on_attach is because I felt it's the right place to call flutter-tool setup function.

So you think that this is why the previous issue happend? flutter-tools setup function was called on startup, and lspconfig then got called on buffer attach

**Comment by akinsho** [comment]
@tami5 yeah probably since I've seen other people do this, this plugin starts and manages the dartls client, so basically it takes over `lspconfig`'s job as far as dart is concerned, you should remove all dart config from your lspconfig settings and only use `flutter-tools` to manage dart. Otherwise you'll have two clients running both trying to respond to things

**Comment by tami5** [comment]
hmmm yah, you ware right flutter tools was no longer working.

Now everything works okay, I had to change how I setup lsp and exposed capabilities and handlers to be added to the setup function. 

:D it's a bit wired that you choose to do it that way, but I'm sure it had to be done so users won't need to deal with low level stuff.

**Comment by tami5** [comment]
@akinsho does extract lsp actions work for you?

**Comment by akinsho** [comment]
Yeah I went back and forth on how to structure it but actually I took inspiration and motiviation from `nvim-jtdtls` and `nvim-metals` who both do it that way i.e. they start and maintain the server themselves. Gives more flexibility and less of a dependency in this plugin.

Re. extract actions It's one of the issues I'm trying to fix, it hasn't worked for me since I moved from `coc` did it work for you in `lspconfig`? I don't think it did for me. I can't figure out what's going wrong there though, since I use the same capabilities as lspconfig and if anything have added more options so not sure
