### ISSUE TITLE
Flutter sdk is not starting 

### ISSUE THREAD

**Issue by RomjanHossain** [akinsho/flutter-tools.nvim#47]
this is my config init.lua config
```
require'lspconfig'.dartls.setup{
  filetypes = {"dart"},
  init_options = {
    closingLabels = false,
    flutterOutline= true,
    onlyAnalyzeProjectsWithOpenFiles = false,
    outline=false,
    suggestFromUnimportedLibraries = true,
  }
}

require("flutter-tools").setup {
  experimental = { -- map of feature flags
    lsp_derive_paths = false, -- experimental: Attempt to find the user's flutter SDK
  },
  debugger = { -- experimental: integrate with nvim dap
    enabled = false,
  },
  flutter_path = "/opt/flutter/bin/flutter", -- <-- this takes priority over the lookup
  flutter_lookup_cmd = 'flutter', -- example "dirname $(which flutter)" or "asdf where flutter"
  widget_guides = {
    enabled = false,
  },
  closing_tags = {
    highlight = "ErrorMSG",
    prefix = ">",
    enabled = true,
  },
  dev_log = {
    open_cmd = "tabedit", -- command to use to open the log buffer
  },
  outline = {
    open_cmd = "30vnew", -- command to use to open the outline buffer
  },
  lsp = {
    settings = {
      showTodos = true,
      completeFunctionCalls = true,
    }
  }
}

require("telescope").load_extension("flutter")
```

![Untitled](https://user-images.githubusercontent.com/47692261/118382799-a9da6800-b61a-11eb-880d-fac9b4ccbc5e.png)

**Comment by akinsho** [comment]
@RomjanHossain there are a few issues with your config, you should *not* be trying to also start `dartls` with lspconfig. The readme explains that this plugin is already starting dartls itself so the user should not do that with lspconfig.


Both of the values below should not both be filled out only one or the other should be filled out, it might be a good idea to go through the README again since it also explains that the flutter lookup command should be a shell command that returns the path to your flutter binary. 
```
  flutter_path = "/opt/flutter/bin/flutter", 
  flutter_lookup_cmd = 'flutter',
```
In your case **either** specify the absolute path as you have done (although that path looks strange i.e. a top level directory called opt) or a command that if you executed it in the terminal would return the full path to fullter

**Comment by RomjanHossain** [comment]
I removed this part from the config as the README.md said it starts with flutter-tools.
```
require'lspconfig'.dartls.setup{
  filetypes = {"dart"},
  init_options = {
    closingLabels = false,
    flutterOutline= true,
    onlyAnalyzeProjectsWithOpenFiles = false,
    outline=false,
    suggestFromUnimportedLibraries = true,
  }
}
```

and I tried to get my flutter absolute path by
`which flutter` and it returns `/usr/bin/flutter'.

I added it to my config
```
  flutter_path = "/usr/bin/flutter", 
  flutter_lookup_cmd = 'flutter',
```
but still not working.........! I'm sorry but am I doing this right.

**Comment by akinsho** [comment]
@RomjanHossain tbh if your flutter is installed in a normal local **and** is in your `$PATH` then you don't need to specify flutter path or lookup_cmd but importantly you **should not** specify both, the lookup cmd in your example is *wrong* because it is not a shell command that will return your flutter path. Try to remove both options and see if that works. Also please verify that flutter is part of your `$PATH` there are instructions on how to add it to your path on the flutter website's installation section.

**Comment by RomjanHossain** [comment]
removing both lines shows "Error running flutter SDK" and only removing `flutter_lookup_cmd='flutter'` doesn't show this error. 

and in my path `echo $PATH | grep flutter` i found flutter in `/opt/flutter/bin` dir and `which flutter` shows `/usr/bin/flutter` dir. 
I tried both path `/opt/flutter/bin/flutter` and `/usr/bin/flutter` but it shows the same error.
btw, I use manjaro and I installed flutter from AUR -> `yay -S flutter`.

**Comment by akinsho** [comment]
@RomjanHossain tbh I have no idea how manjaro lays out its packages, I'm not at all clear on why two different paths are being returned i.e. a different one in your path than the result of `which` are you sure there is only one installation on your system?

In either case can you try `flutter_lookup_com = 'which flutter'` and *no flutter_path*, see if that works. If not try a plain `/opt/flutter/bin/flutter -h` *in the terminal*, does that work? if it does try that in your `flutter_path` if not try `/usr/bin/flutter -h` if that works then try that in the flutter path.

If none of that works (this is a long shot) try `flutter sdk-path` to see if that prints anything. If the command exists then try setting `derive_lsp_path` to true (details in the README).

To be clear about what this is all about. You need to tell this plugin where to find flutter so it can run flutter commands. In most normal cases flutter it's just somewhere like `/usr/bin/flutter` and if you run `/usr/bin/flutter -<some-cmd>` that should work and should also be enough for this plugin. By default if a user has installed flutter and it is in the path neovim should be able to find it by first checking `executable('flutter')` that should be `1` then getting the path via `exepath('flutter')` special config should only be for complex setups (maybe this is your case).

**Comment by RomjanHossain** [comment]
i tried `flutter_lookup_cmd='which flutter` with no _flutter path_ but it doesn't work. 
AND `/usr/bin/flutter -h` + `/opt/flutter/bin/flutter -h` both works on the terminal :). as previously said I tried adding both path to the _flutter path_ but no luck.

`flutter sdk-path` saya command error. `flutter doctor -v` shows 
`Flutter version 2.0.6 at /opt/flutter` <- this location.

**Comment by RomjanHossain** [comment]
After creating a new flutter project `flutter create test` and opening the project file in neovim works. But as I go to my previous project and open it by neovim doesn't woks.

I'm testing `flutter-tools` on my previous project and it shows those error but not in the new one.

Thanks
