### ISSUE TITLE
Closing Tags, Widget guides and Outline Window not working

### ISSUE THREAD

**Issue by omarbassam88** [akinsho/flutter-tools.nvim#53]
The Cloasing Tags don't show up. The Widget guides as well, Even though I explicitly set them to true in my config as follows:
  widget_guides = {
    enabled = true,
  },

Also, When trying to open the Flutter outline :FlutterOutline it says:
"Sorry There's no outline for this file. "
I did try them with different files and in different projects.

**Comment by omarbassam88** [comment]
Thank you for your Reply. I'm quite new to NeoVim and have been trying to setup my personal configuration in Lua inspired by Lunar Vim and doom-nvim.

This is how I setup my flutter-tools
```Lua
require("flutter-tools").setup {
    flutter_path = "echo /home/omar/snap/flutter/common/flutter/bin/flutter",
    flutter_lookup_cmd = "echo /home/omar/snap/flutter/common/flutter/",
    widget_guides = {enabled = true},
    outline = {
        open_cmd = "30vnew" -- command to use to open the outline buffer
    },
    closing_tags = {
        highlight = "ErrorMsg", -- highlight for the closing tag
        prefix = ">", -- character to use for close tag e.g. > Widget
        enabled = true -- set to false to disable
    },
}
```
The Diagnostics and Formatting are working fine

![image](https://user-images.githubusercontent.com/49006410/119797954-01aa8600-bedb-11eb-9614-69e8849cacd6.png)

Here's My Full Configuration if you need to have a look at.

https://github.com/omarbassam88/nvim

**Comment by akinsho** [comment]
@omarbassam88 you should not need to setup both a `flutter_path` and a `flutter_lookup_cmd` only one is necessary. If you are using snap then you can just use the `derive_lsp_path` since that will figure out the location for snap (it's what I use).

Few things to check, are you sure `dartls` is *Not* being configured also via `lspconfig` it's important that it is Not.
There's also a delay to seeing the `widget_guides` and the outline, you need to wait a few mins after the lsp is first initialised, but if you're never seeing them then something else might be going on.
What version of neovim are you using? the `nightly`? you need a recent nightly for this plugin to use widget guides.

**Comment by omarbassam88** [comment]
Thank you for your reply. I'm new to NeoVim and want to switch away from VSCode.
The Experience so far with this plugin is great, The issues I have are only aesthetics and would be great to get it working.

My NeoVim Version is:
NVIM v0.5.0-dev+1357-g192f89ea1

If the dartls is not managed by `lspconfig` I don't get any lsp features at all.

The `derive_lsp_path`  doesn't load the Flutter tool at all. The only thing that worked was specifying flutter_path to:
`/home/omar/snap/flutter/common/flutter/bin/flutter`

**Comment by akinsho** [comment]
@omarbassam88 if the only way that you are seeing lsp features is with `lspconfig` then this likely means this plugin isn't doing anything/working at all on your system. This probably is because it isn't finding the path to the lsp correctly. Can you run `flutter sdk-path` in the terminal and see what that gives? If it gives nothing it likely means that you are running maybe an old version of flutter (assuming that you are on linux which you must be to be using snaps).

To be clear the actual correct configuration for deriving the lsp path is
```lua
   experimental = {
       lsp_derive_paths = true
    },
```

Also whilst using this plugin you *Must* disable dartls via `lspconfig` it's an either or situation you can use lspconfig for other languages but if using flutter tools you have to disable it, then see what the actual situation with this plugin is.

Not sure if you were using the config from the README or what I wrote (which was wrong and just from memory)

**Comment by omarbassam88** [comment]
I'm Running PopOS 20.10

The Flutter version I'm using is: 
`Flutter 2.3.0-13.0.pre.146 • channel master`

The output of `flutter sdk-path` is:
`/home/omar/snap/flutter/common/flutter`

Which is what I put in the flutter tools `flutter_lookup_cmd`.

I did set up the `lsp_derive_paths` exactly as you mentioned. It still doesn't work on its own.

my current configuration for flutter-tools is as follows:
```Lua
require("flutter-tools").setup {
    experimental = { -- map of feature flags

        lsp_derive_paths = true -- experimental: Attempt to find the user's flutter SDK
    },
    flutter_lookup_cmd = "echo /home/omar/snap/flutter/common/flutter/",
    widget_guides = {enabled = true},
    outline = {
        open_cmd = "30vnew" -- command to use to open the outline buffer
    },
    closing_tags = {
        highlight = "ErrorMsg", -- highlight for the closing tag
        prefix = ">", -- character to use for close tag e.g. > Widget
        enabled = true -- set to false to disable
    },
}
'''

**Comment by akinsho** [comment]
@omarbassam88 you shouldn't also set the `flutter_lookup_cmd` if you are using `lsp_derive_paths` tbh I should document this better but only one mechanism involving getting the path should be set. I need to add an error/warning when inspecting a user's config so that it makes it clear which options should be mutually exclusive.

Not sure if that will help here but they definitely shouldn't both be set since the plugin doesn't expect that and could error because of it.

**Comment by omarbassam88** [comment]
I had to use the `flutter_lookup_cmd` because if I use `lsp_derive_paths` options only. It doesn't work and I get an "Error Running Flutter" When Trying to Run the command :FlutterRun.

So, I will hoave to stick with `flutter_lookup_cmd` option only for now as this is the only option that currently works to run the Flutter Tools.

**Comment by akinsho** [comment]
I've refactored the code and the docs are a bit out of date. Currently the `lsp_derive_paths` does nothing really if you are on `linux` and you *Don't* specify a `lookup_cmd` or `flutter_path` it will try and derive it anyway.

Since you use snap then technically you shouldn't have to set any path things at all, e.g. `lsp_derive_paths` or `flutter_lookup_cmd` or `flutter_path` it should just work without any of that but for reasons I don't understand it isn't all it does is set the flutter lookup command to `flutter sdk-path`. If that is returning the correct value on your system that should work 🤷🏾 .

If it doesn't then you only need to set one i.e. the full path to the binary or a command which returns it. Please try setting only the the flutter path to the full path to the binary in your example above you are using the path to the flutter installation not the `binary` it should have another `flutter/common/flutter/<bin>` can't remember but you should be able to run `<path-to-flutter> --version` and that should work.

In any case if you manage to get any single one of those working that's really all there should be to it i.e. outline and guides should work I really don't know what could be happening if it still doesn't

**Comment by omarbassam88** [comment]
I found the fix now.

I was running flutter channel `master`. When I switched to `stable` everything magically started working.

May be you should add this as a requirement in the README.md

Thank you again for the great plugin, and sorry for wasting your time.

**Comment by akinsho** [comment]
@omarbassam88 that's a good idea, the README is due an update. Tbh I don't ever use the master channel so I didn't realise there'd be a difference in behaviour tbh

**Comment by akinsho** [comment]
Gonna close this now as I've updated the README 👍🏾
