### ISSUE TITLE
Error running flutter sdk-path

### ISSUE THREAD

**Issue by PabloAbreuC** [akinsho/flutter-tools.nvim#54]
I see this error message when i try to use something from telescope integration (List emuladors, devices, etc)

**Comment by akinsho** [comment]
@PabloAbreuC thanks for checking out the plugin. This is probably because I made an assumption in the plugin that if a use has snap installed they probably installed `flutter` via snap in which case they should have access to `flutter sdk-path` as  command.

Can you try the command in your terminal and see if it works? How did you install flutter and what version is it?

**Comment by PabloAbreuC** [comment]
I had directly installed the source code and added it to my path, now with snap it works normally

**Comment by searleser97** [comment]
I am getting the same error and I installed with snap
