### ISSUE TITLE
Support custom sdk paths

### ISSUE THREAD

**Issue by CarlosNihelton** [akinsho/flutter-tools.nvim#55]
First of all thank you for this great job. This is a very promising plugin.
I'm having headaches, though, to make the language server to work. Flutter commands are working fine, but LSP doesn't.

When I check the LSP log it is complaining about the dart snapshot. I'll still check yet, but I suspect that is caused by the fact that I have Dart inside Flutter SDK and also standalone.

That being said, I'd like to be able to select the SDK folder (instead of the flutter path only) to make sure the plugin is invoking the analysis server I want.

**Comment by akinsho** [comment]
Hi @CarlosNihelton, so you should already be able to specify the flutter path you want to use by specifying a `flutter_path` which should be a path to the flutter binary. The plugin will then use the flutter path to find the dart sdk path or if dart is executable it will find it that way. It really shouldn't/doesn't care about having dart in two places since it will 1.) try to use dart as part of flutter if that doesn't work then 2.) try to use the dart executable.

Have you tried setting either `flutter_path` or `flutter_lookup_cmd` please note you should *not set both* only one. The command is primarily if you use something like `asdf`.

Finally if none of the above works you can actually pass the command you want the lsp to use directly using 

```lua
{
-- rest of config
  lsp = {
    cmd = {"<LSP-path>", "<other-args>"}
  }
}

**Comment by CarlosNihelton** [comment]
Hi @akinsho ! 

I tried setting those variables before, the one thing I didn't try was to set the lsp cmd. But after removing dart-sdk (the standalone one) the plugin worked like a charm. I believe some confusion caused by symlinks created during installation of those SDKs in my Arch Linux. Their folders go to /opt, but symlinks are created into /usr/bin.

Thanks again for the great job! I'm enjoying this plugin!
