### ISSUE TITLE
Lagging when navigating Flutter SDK

### ISSUE THREAD

**Issue by RobertBrunhage** [akinsho/flutter-tools.nvim#57]
This may not be related to `flutter-tools` but instead https://github.com/hrsh7th/nvim-compe but would love to hear if you have a solution for it.

When navigating the Flutter source code, it starts lagging immensely which I think is related to how there are errors everywhere and this also hinders navigating deeper in the SDK, for example navigating to `StatefulWidget` from here.
![image](https://user-images.githubusercontent.com/26344867/121318737-cf9e1880-c90b-11eb-9da5-e8a2aa75d905.png) 

Do you have this issue? Or do you have any specific configurations done to not get errors when navigating the Flutter SDK?

**Comment by akinsho** [comment]
@RobertBrunhage thanks for raising this 👍🏾 I hadn't really paid too much attention but I was able to reproduce this. I don't think it relates to `compe` since it's activities are primarily through completion so any lag it causes would be during completion.

I think the main issue here is *possibly* how I've set up the language server. At the moment it doesn't exclude any folders from being analysed so when you jump into an sdk package it tries to analyse the entire folder i.e. all the packages from wherever it determines the root to be which is going to a) be too many files and b) not useful since you don't need analysis like diagnostics for an sdk package.

I've tried locally using the 
```
lsp = {
   settings = {
      analysisExcludedFolders = {vim.fn.expand("$HOME/flutter/packages")}
  }
}
```

which seems to stop the lag on my machine. Can you try adding the path to your flutter binary (if you use a mac and it's installed in your home dir) you can just use exactly what I used there,
to see if it makes it less laggy on your end?

If that works then I will add this in as a default so people can jump into the sdk definitions without lag.

**Comment by RobertBrunhage** [comment]
Awesome, that makes a lot more sense!

I tested it out and worked great, no more lag!

I tried defining it like this which didn't work 

```
require("flutter-tools").setup{ 
  lsp = {
    on_attach = on_attach,
    settings = {
      analysisExcludedFolders = {vim.fn.expand("%HOMEDRIVE%/src/flutter/packages")}
    }
  }
} 
```

but replacing %HOMEDRIVE% with just C: worked well (I am using Windows).

**Comment by rlch** [comment]
Just a tip; I would also recommend adding `vim.fn.expand("$HOME/flutter/.pub-cache")` to this table to stop analysis on pub.dev packages.

This really improved my performance :)

**Comment by akinsho** [comment]
Good shout @rlch, I've added that in as well. Tbh I think long term there's a better way to do this e.g. just not analysing anything that's not in the current workspace 🤔

**Comment by RobertBrunhage** [comment]
@akinsho any plans for adding this to only analyze in the current workspace? Getting this same issue when I navigate to packages code that I depend on.

**Comment by akinsho** [comment]
@RobertBrunhage I still don't really have any clue how I would do that, there is no explicit option in the [lsp spec](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md) that provides this. `onlyAnalyzeProjectsWithOpenFiles` is the closest thing that sounds right but it won't actually stop huge files or their containing projects being analysed. If anyone has a good suggestion 🤷🏿‍♂️
