### ISSUE TITLE
Unable to Launch Emulators from FlutterEmulators

### ISSUE THREAD

**Issue by jonathan-raines** [akinsho/flutter-tools.nvim#60]
I can see the emulators when executing `Flutter emulators`.
![image](https://user-images.githubusercontent.com/5840124/122571839-c51e0600-d012-11eb-80d9-c834e98d2c05.png)
But pressing enter on either option does nothing. No error messages. Nothing. The window just stays where it is. I can continue to scroll through the options but nothing happens.

These are the android tools I am using
![image](https://user-images.githubusercontent.com/5840124/122572127-0f06ec00-d013-11eb-9c96-0b21c39abb0d.png)

And here is the flutter package I am using
![image](https://user-images.githubusercontent.com/5840124/122572205-22b25280-d013-11eb-9daf-731118cb6cdc.png)

Running `emulator @default` on the command line does work.
![image](https://user-images.githubusercontent.com/5840124/122572387-4f666a00-d013-11eb-8ca4-1f68760cc968.png)

If there's anything more I can provide, please let me know!

**Comment by akinsho** [comment]
Hi @jonathan-raines,

Can you paste the output of the `flutter emulators` command on your machine. The plugin works by trying to extract the device id from the output of that command. In my case on my current machine I get
```
➜ flutter emulators
3 available emulators:

apple_ios_simulator • iOS Simulator        • Apple  • ios
Pixel_3a_API_29     • Pixel 3a API 29      • Google • android
Pixel_3a_Android_Q_ • Pixel 3a (Android Q) • Google • android
```

It could be that somehow this information is either unavailable or the parsing fails silently because the emulators don't match the above structure.

Can you try also running `flutter emulator --launch <desired-id>` to confirm that that works

I'm not sure what the `@` syntax is or how `emulator @default` works is that just short for `flutter emulators --launch @default` otherwise what binary is that using to run the emulator?

**Comment by jonathan-raines** [comment]
![image](https://user-images.githubusercontent.com/5840124/122579961-13370780-d01b-11eb-87c6-3159bee0f3e1.png)

Did you create the emulators through Android Studio's avdmanager? Maybe that's my issue. I created them from the command line using `avdmanager create avd -n default -k "system-images;android-S;google_apis_playstore;arm64-v8a" `

I was trying to avoid Android Studio because I only really used it for created emulators, but that may be what i need to do.

**Comment by akinsho** [comment]
@jonathan-raines that's interesting, I do use android studio for that. I'm guessing it's likely because the data you've got is missing the `Google`/`Android` vendor bit maybe so the parsing is possibly failing to pick out the the correct ID key. I'll try seeing if I can reproduce the issue when I have time. In the meantime you can try using android studio just to see if the emulators it creates work for you.

Also are you able to run the emulators you listed above with the flutter emulator command?

**Comment by jonathan-raines** [comment]
`flutter emulators --launch default` does launch the emulator

**Comment by akinsho** [comment]
@jonathan-raines just tried this out and added a test case for it and don't believe it is actually the parsing. Can you paste the text of the output of running `echo b:devices` whilst inside the emulator selection window? It should look like (roughly)
```
{'• Pixel_3a_API_30_x86 • Google': {'id': 'Pixel_3a_API_30_x86', 'name': 'Pixel_3a_API_30_x86', 'platform': 'Google', 'system': 'android', 'type': 1}, '• Pixel 4 (android 11) • Googl
e': {'id': 'Pixel_4_android_11_', 'name': 'Pixel 4 (android 11)', 'platform': 'Google', 'system': 'android', 'type': 1}}
```

**Comment by jonathan-raines** [comment]
`{'• default • ': {'id': 'default', 'name': 'default', 'platform': '', 'system': 'android', 'type': 1}, '• Pixel 4a API 30 • G
oogle': {'id': 'Pixel_4a_API_30', 'name': 'Pixel 4a API 30', 'platform': 'Google', 'system': 'android', 'type': 1}}     `

You are seeing the Pixel 4a device because I downloaded Android Studio as a band aid.

**Comment by akinsho** [comment]
@jonathan-raines it's a bit unlikely, but can you try the latest commits and see if they resolve this issue. The slightly dumb mechanism I'm using to get each line's info might have been broken for you, since there was no platform. In either case, you shouldn't see a second dot printed when there is no platform.

**Comment by jonathan-raines** [comment]
I was just trying it but I'm getting 
![image](https://user-images.githubusercontent.com/5840124/122788163-ad958600-d27b-11eb-97c6-03b561ad2f8e.png)

I'm on the latest flutter-tools version. I ran `PackerSync` just to make sure. I also uninstalled and reinstalled the plugin

**Comment by akinsho** [comment]
@jonathan-raines I added a note to the README but maybe need a better way to signal this stuff. The TLDR is you need to update your version of nightly neovim. The border style that this plugin is referencing was added about a week ago.

I don't think your neovim is actually on the latest version can you paste the output of `:version` here

**Comment by jonathan-raines** [comment]
:version                                                                                                                     
NVIM v0.5.0-dev+1373-g68d40388f                                                                                              
Build type: RelWithDebInfo                                                                                                   
LuaJIT 2.1.0-beta3                                                                                                           
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow 
-Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto 
-DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home
/jraines/neovim/build/config -I/home/jraines/neovim/src -I/home/jraines/neovim/.deps/usr/include -I/usr/include -I/home/jrain
es/neovim/build/src/nvim/auto -I/home/jraines/neovim/build/include                                                           
Compiled by jraines                                                                                                          
                                                                                                                             
Features: +acl +iconv +tui                                                                                                   
See ":help feature-compile"                                                                                                  
                                                                                                                             
   system vimrc file: "$VIM/sysinit.vim"                                                                                     
  fall-back for $VIM: "/usr/local/share/nvim"                                                                                
                                                                                                                             
Run :checkhealth for more info

**Comment by akinsho** [comment]
@jonathan-raines my build from this morning is on `NVIM v0.5.0-dev+nightly-797-gb585f723bc` not sure when you last built nvim or how you are downloading it, I think some of the mechanisms for installing the nightlies don't always install the most recent. The quickest solution for you would be to set
```lua
-- in config as a top level key
ui = {
  border = "single"
}
```
Regarding the issue it is definitely due to an nvim version issue as I've hit this several times across different plugins.

**Comment by jonathan-raines** [comment]
Okay I can confirm this issue is fixed. I downloaded the most recent app image which is `NVIM v0.5.0-dev+1429-gb585f723b` and I can now launch emulators that were created via the command line.

**Comment by akinsho** [comment]
Awesome glad it fixed it. Regarding the nvim version I think I read an issue a while back about something being wrong with the app images but tbh I didn't read it in detail. Can you check the documentation on your version of neovim to see if it includes some changes i.e. under `:help nvim_win_open` there is a border section which should include the available styles. Does your version of vim include the `rounded` text?

I might just make the default the straight borders to avoid this issue and anyone on the latest nvim can manually set the curved style if they want.
