### ISSUE TITLE
Invalid border style: "rounded"

### ISSUE THREAD

**Issue by Charly6596** [akinsho/flutter-tools.nvim#61]
![image](https://user-images.githubusercontent.com/13708100/122693331-b2d1e100-d239-11eb-8806-dae13d875be6.png)
I'm getting that error after updating, caused by this default config value
https://github.com/akinsho/flutter-tools.nvim/blob/a6e8b7de3d447fc2c69c6a0ceba6c6fd277f43cc/lua/flutter-tools/config.lua#L51

I'm using `NVIM v0.5.0-dev+1311-gf8173df4d`
Probably `rounded` was added in a later version?

Not a big deal. Changing it to anything listed in `:h nvim_open_with()` solves it. (`shadow` for example)
It would be nice to have something in the readme mentioning it, for those having this issue in the future.

**Comment by akinsho** [comment]
@Charly6596 yep this is due to the addition of this key in a recent version of neovim nightly so updating the version will fix this. Tbh I contemplated adding it to the README, but until 0.5 is released this plugin will be following new changes hopefully there won't be too much more, and the plugin already states that a recent version of neovim nightly is required.

I'll add in a notice if I get the chance but rather than a new README every time nightly changes I'd rather encourage people to keep things up to date to till 0.5.

**Comment by akinsho** [comment]
Fixed in the most recent commit, I added a notices section and updated the requirements to indicate that people should keep their nightlies up to date until 0.5. is stable to avoid other breakages but tbh I think it's moot since 0.5 has been feature frozen
