### ISSUE TITLE
How to enable auto complete

### ISSUE THREAD

**Issue by barun108** [akinsho/flutter-tools.nvim#65]
Can you provide any working config file for enabling auto complete ?
It shows name of widget and classes but doesn't generate any code snippets.

**Comment by akinsho** [comment]
@barun108 auto complete functionality is separate to this plugin. I highly recommend using nvim-compe and having a read through the README to set things up including snippets.

I can't provide an example in this plugin because users have to set up completion separately since that is not specific to flutter but to all your other languages. Also users can use whatever plugin they want and I can't provide configs for all of them.

**Comment by barun108** [comment]
I am using it lunar vim , other users are also having issues with autocomplete
hope to sort it out soon
by the way I asked same question in Reddit also 

Thanks for this plugin,

**Comment by akinsho** [comment]
Gonna close this out as I feel it's been answered.
