### ISSUE TITLE
[Question]: How to get started after forking this project? 

### ISSUE THREAD

**Issue by miriam-z** [akinsho/flutter-tools.nvim#80]
thank you

Mac OSX Big Sur
nvim: 0.5

**Comment by akinsho** [comment]
Hi @miriam-z, what do you mean? get started doing *what*? are you trying to contribute? or are you trying to use this plugin?

**Comment by miriam-z** [comment]
Yes trying to use this plugin, how to launch flutter run -v, the same way or we have nvim commands for it?

**Comment by akinsho** [comment]
@miriam-z I'm a bit confused, in order to install a neovim plugin you should either use a plugin manager like `vim-plug` or `packer.nvim` or you can use native packages `:h packages` and clone this plugin to the start directory of your package path. Forking it isn't normally the path to run a vim plugin

**Comment by akinsho** [comment]
I'm going to close this out, due to inactivity. FWIW forking this project is not a good way to get started using it. You need to look at a neovim package manager like `vim-plug` or `packer` and use either to install this plugin. Then have a read through the read me to get an understanding of how it works
