### ISSUE TITLE
[Bug]: log not scrolling automatique after any update of log

### ISSUE THREAD

**Issue by ayoubelmhamdi** [akinsho/flutter-tools.nvim#81]
- like terminal , any `cli-app` can show last line of their log file , but this plugin after any update of log , i should be scroll manually to end of tab to view last update  
- also i can't clear tab scren of  log file !

**Comment by akinsho** [comment]
@ayoubelmhamdi 

* `like terminal , any cli-app can show last line of their log file , but this plugin after any update of log , i should be scroll manually to end of tab to view last update.`
  The log buffer will not scroll whilst a user is inside the buffer. I did this on purpose because I 	find that behaviour unacceptable since you can't move around the log buffer correctly if it is constantly being moved around whilst you are in it. If this is not autoscrolling whilst you are not in the buffer then that is a bug and I would welcome a PR 🙏🏿 

* `also i can't clear tab scren of log file !`
  You can clear the log screen using the `FlutterToolsClearLog` command using either the telescope extension or checking this command in the command line. I might have spelt it wrong so you have to check for the correct one.

**Comment by ayoubelmhamdi** [comment]
i want to try `autocmd buffer focuse name __FLUTTER_LOG__` but i should be search to how vim detect the buffer name it's focused or not

**Comment by akinsho** [comment]
I've tweaked this and verified that it works, so it should now scroll down, think it was buggy before. It still won't scroll whilst you are in it. This is non-negotiable behaviour to me 🤷🏿‍♂️
