### ISSUE TITLE
[Question]: Using flutter tools with nvim-lspconfig 

### ISSUE THREAD

**Issue by ldelossa** [akinsho/flutter-tools.nvim#87]
Hello,

I currently use nvim-lsp to setup all language servers. It's also where all my keymaps for LSP client procedures are registered. 

I also import and use this plugin. It appears that I'm actually launching two dartls language servers now. Is this correct?

**Comment by akinsho** [comment]
@ldelossa nope you should not configure the language server in both plugins

There's a note about this in the README https://github.com/akinsho/flutter-tools.nvim#warning
You should remove where you are setting up dartls via lspconfig

**Comment by ldelossa** [comment]
Got it. 

Most individuals will have their key bindings for lsp setup like this: 
https://github.com/ldelossa/dotfiles/blob/master/nvim/nvim-lsp.lua#L25-L44

If "dartls" does not wind up in lspconfig the "on_attach" won't be called. 

Do you have an alternate suggestion on how to perform this "on_attach" when using flutter-tools.nvim

**Comment by akinsho** [comment]
@ldelossa this is also in the README, you can pass the on attach function via
```lua
lsp = {
 on_attach = my_on_attach
}
```

**Comment by ldelossa** [comment]
@akinsho wouldn't it make more sense to simply not run the "dartls" if it already is attached to the buffer?

**Comment by akinsho** [comment]
@ldelossa that's a lot more complicated than it sounds, would actually not allow this plugin to work as needed and is ultimately not something I want for this plugin.

Any user can have any number of lsp clients attached to a buffer, and it isn't really up to this plugin to start messing around with that. For example, I run `null-ls` in most buffers. If a user has dartls running through lspconfig it means that this plugin can't manage the lsp and do things like derive the correct path for the flutter binary or add/manage settings easily. In the case of lspconfig it manages the clients on its own, so it also means it will take over functionality which this plugin manages as well and based on plans the nvim team have a lot of the logic in lspconfig will eventually move to nvim core so essentially running dartls both there and here is just a duplication rather than something that it makes sense long term to work around.

**Comment by akinsho** [comment]
I'm going to close this out now since I believe the question has been answered.
