### ISSUE TITLE
[Bug]: Can't hot reload or hot restart with DAP

### ISSUE THREAD

**Issue by DanielCardonaRojas** [akinsho/flutter-tools.nvim#91]
Can't hot reload or hot restart when running the flutter through nvim-dap,
the documentation says that  when debugging is enabled  the app should be ran with `:lua require('dap').continue()<CR>`. 

This results in a log message: `[Flutter-tools]: Sorry! fFutter is not running`

**Comment by akinsho** [comment]
Hi @DanielCardonaRojas thanks for reporting this. There are a few issues with using DAP I still need to work out, which require a bit of know how regarding dap's internals I don't have quite yet. Will leave this open till I or anyone else who might want to contribute has time to look into a good solution.

FWIW I think the issue is that dap is starting the app itself when continue is used which means that this plugin has no real connection to the process it creates and no way of knowing that it even exists or how to interact with it.

@DanielCardonaRojas you might be able to get this work by starting your app and using the `attach` option that should be presented to you when you hit continue instead of other option (I forget the name).

I think the solution lies with only providing an attach option so that this plugin can create and manage the process and dap just attaches to the process we are managing

**Comment by clement-buchart** [comment]
Hello @akinsho, 

I've been poking around at this and I thought you (or people following this issue) might be interested.

- The process you describe (starting the app via the `flutter-tools.nvim` and attaching to the process) is achievable and does work with 2 caveats :
    - It seems to work only for hot reload, for hotRestart I get
```
Performing hot restart...                                       
E/flutter ( 8452): [ERROR:flutter/runtime/dart_isolate.cc(170)] Could not prepare isolate.
E/flutter ( 8452): [ERROR:flutter/runtime/runtime_controller.cc(382)] Could not create root isolate.
Restarted application in 1,003ms.
Application finished.
hot restart failed to complete: _flutter.runInView: (-32000) Could not run configuration in engine.
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1626:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2109:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2080:14)
#3      VmService.callMethod (package:vm_service/src/vm_service.dart:2062:12)
#4      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:451:28)
#5      FlutterVmService.runInView (package:flutter_tools/src/vmservice.dart:530:11)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#7      HotRunner._launchInView (package:flutter_tools/src/run_hot.dart:534:5)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#9      HotRunner._launchFromDevFS (package:flutter_tools/src/run_hot.dart:554:5)
<asynchronous suspension>
#10     HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:637:5)
<asynchronous suspension>
#11     HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:751:16)
<asynchronous suspension>
#12     HotRunner.restart (package:flutter_tools/src/run_hot.dart:698:38)
<asynchronous suspension>
#13     TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1619:40)
<asynchronous suspension>
#14     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1659:7)
<asynchronous suspension>
```
I'm not sure that this is supported so that might not be actionable.
    - It needs 2 user interactions, start and then attach. It could be reduced to a single one if we introduced some sort of callback that would be passed the run command and would be executed when we see `An Observatory debugger and profiler` in stdout. But that is a bit hackish. 
      
- An alternative would be to use this flag from flutter : `--pid-file : Specify a file to write the process ID to. You can send SIGUSR1 to trigger a hot reload and SIGUSR2 to trigger a hot restart. The file is created when the signal handlers are hooked and deleted when they are removed.`. `flutter-tools.nvim` could use this arg to have a way to send hotReload or hotRestart event to the flutter process, without a handle on the process tty.
- Another alternative is to send the hotReload / hotRestart request via the dap adapter. Is is actually quite easy to do : `lua require('dap').session():request('hotRestart')`.

I will be using this last method a bit and can report back on how it goes if you want.

I'm thinking if all goes well, one could make it so that `flutter-tools.nvim` allows 2 strategies for starting and driving flutter apps : the current one that starts the process and send keystroke to the tty and another one using `nvim-dap` and `Dart-Code` for those willing to install and set it up.

**Comment by akinsho** [comment]
@clement-buchart that looks really cool, I think I'd ideally want a mechanism like that to be behind an option so that this plugin continues to function as expected without `dap` and not have it become an implicit dependency. I think abstracting the process being interacted with away somehow would be ideal. so it would be like
```lua
-- process.lua
function M.restart()
 if config.process == 'dap' then
  dap.send('blah')
 else
  Job:send('restart')
 end
return M
```

Then all the direct interactions with the process could be replaced with interactions with the `process` module.

Just as an idea, and some pseudo code not sure if there'd be issues with that approach but think it'd simplify interacting with it in different ways

**Comment by clement-buchart** [comment]
Hello, 

I finally found some time to tackle this.

I opened the PR, feedback welcome.
